fix: app arch name

diff --git a/products/coco-app/snapcraft-with-down.yaml b/products/coco-app/snapcraft-with-down.yaml
--- a/products/coco-app/snapcraft-with-down.yaml
+++ b/products/coco-app/snapcraft-with-down.yaml
@@ -29,8 +29,8 @@ package-repositories:
 parts:
   coco: 
     plugin: dump
-    # $SNAPCRAFT_PROJECT_DIR/snap_sources/__APPNAME__.deb
-    source: snap_sources/__APPNAME__.deb
+    # $SNAPCRAFT_PROJECT_DIR/snap_sources/__APPARCHNAME__.deb
+    source: snap_sources/__APPARCHNAME__.deb
     source-type: deb
     # No override-build is needed to extract the .deb
     # plugin: dump with source-type: deb handles this.
@@ -40,14 +40,14 @@ parts:
       set -eu
       export RELEASE_URL="https://release.infinilabs.com/coco/app/stable"
       echo "Repack Coco AI App with ${SNAPCRAFT_PART_INSTALL} at ${PWD} .."
-      mkdir -p snap_sources && wget -q -O snap_sources/__APPNAME__.zip $RELEASE_URL/__APPNAME__-deb-linux-__ARCH__.zip
-      unzip /tmp/__APPNAME__.zip -d snap_sources && mv snap_sources/*.deb snap_sources/__APPNAME__.deb || true
-      if [ -e snap_sources/__APPNAME__.deb ]; then
+      mkdir -p snap_sources && wget -q -O snap_sources/__APPARCHNAME__.zip $RELEASE_URL/__APPNAME__-deb-linux-__ARCH__.zip
+      unzip /tmp/__APPARCHNAME__.zip -d snap_sources && mv snap_sources/*.deb snap_sources/__APPARCHNAME__.deb || true
+      if [ -e snap_sources/__APPARCHNAME__.deb ]; then
         echo "Extracting deb package to ${SNAPCRAFT_PART_INSTALL} ..."
-        dpkg -x snap_sources/__APPNAME__.deb $SNAPCRAFT_PART_INSTALL
+        dpkg -x snap_sources/__APPARCHNAME__.deb $SNAPCRAFT_PART_INSTALL
         ls -l $SNAPCRAFT_PART_INSTALL
       else
-        echo "Error: snap_sources/__APPNAME__.deb not found!"
+        echo "Error: snap_sources/__APPARCHNAME__.deb not found!"
       fi
 
       if [ -f "$SNAPCRAFT_PART_INSTALL/usr/share/applications/Coco-AI.desktop" ]; then
