chore: fix update build number

diff --git a/.github/workflows/coco-app.yml b/.github/workflows/coco-app.yml
--- a/.github/workflows/coco-app.yml
+++ b/.github/workflows/coco-app.yml
@@ -256,6 +256,11 @@ jobs:
       - name: Init Env
         run: |
           $GITHUB_WORKSPACE/scripts/env-init.sh
+          # Check if jq is installed
+          if ! command -v jq &> /dev/null; then
+            echo "jq could not be found. Please install jq."
+            exit 1
+          fi
           # Setup environment
           current_version=$PUBLISH_VERSION
           if [ -z "$current_version" ]; then
@@ -293,7 +298,6 @@ jobs:
           # Function to fetch signatures
           get_signature() {
             url="$1"
-            echo $url
             # Check if the URL is valid
             if ! curl -sI "$url" | grep "HTTP/1.[01] 200" >/dev/null; then
               echo "Invalid URL: $url"
@@ -338,12 +342,7 @@ jobs:
             }
           }
           EOF
-          cat update.json
-          # Check if jq is installed
-          if ! command -v jq &> /dev/null; then
-            echo "jq could not be found. Please install jq."
-            exit 1
-          fi
+
           # Initialize jq statements
           jq_statements=""
 
@@ -364,6 +363,8 @@ jobs:
           jq_statements+=" .platforms.\"windows-i686\".signature = \"$(get_signature ${RELEASE_URL}/${PRE_UPGRADE_PATH}/Coco-AI_${VERSION}_x86-setup.exe.sig)\" "
 
           # Apply jq statements
-          jq "${jq_statements}" update.json > .latest.json
+          cat update.json | jq "${jq_statements}" > .latest.json
+          cat .latest.json
 
-          oss upload -c $GITHUB_WORKSPACE/.oss.yml -o -k "$PNAME/snapshot/$UPGRADE" -f $GITHUB_WORKSPACE/.latest.json
+          # Upload the JSON file to OSS
+          oss upload -c $GITHUB_WORKSPACE/.oss.yml -o -k "$PRE_UPGRADE_PATH" -f $GITHUB_WORKSPACE/.latest.json
