chore: add some default

diff --git a/.github/workflows/coco-server.yml b/.github/workflows/coco-server.yml
--- a/.github/workflows/coco-server.yml
+++ b/.github/workflows/coco-server.yml
@@ -65,13 +65,15 @@ jobs:
 
       - name: Setup coco server env
         run: |
-          if [[ "${{ inputs.PUBLISH_VERSION }}" =~ ^([0-9]+\.[0-9]+\.[0-9]+)-([1-9][0-9]*)$ ]]; then
-            version="${BASH_REMATCH[1]}"
-            build_number="${BASH_REMATCH[2]}"
-            echo "Build $PNAME with $version-$build_number"
-          else
-            echo "Error: Invalid version string format. Expected X.Y.Z-BUILD_NUMBER." >&2
-            exit 1
+          if [[ -n "${{ inputs.PUBLISH_VERSION }}" ]]; then
+            if [[ "${{ inputs.PUBLISH_VERSION }}" =~ ^([0-9]+\.[0-9]+\.[0-9]+)-([1-9][0-9]*)$ ]]; then
+              version="${BASH_REMATCH[1]}"
+              build_number="${BASH_REMATCH[2]}"
+              echo "Build $PNAME with $version-$build_number"
+            else
+              echo "Error: Invalid version string format. Expected X.Y.Z-BUILD_NUMBER." >&2
+              exit 1
+            fi
           fi
           source $GITHUB_WORKSPACE/scripts/go-init.sh
           $GITHUB_WORKSPACE/scripts/env-init.sh
@@ -169,7 +171,7 @@ jobs:
           node-version: ${{ env.NODEJS_VERSION }}
           cache: 'pnpm'
           cache-dependency-path: "**/pnpm-lock.yaml"
-          
+
       - name: Build coco server
         run: |
           # build web
