chore: fix operatorversion check

diff --git a/.github/workflows/publish-operator.yml b/.github/workflows/publish-operator.yml
--- a/.github/workflows/publish-operator.yml
+++ b/.github/workflows/publish-operator.yml
@@ -16,21 +16,21 @@ on:
         description: 'Publish easysearch'
         required: false
         type: boolean
-        default: false
+        default: true
       PUBLISH_RUNTIME:
         description: 'Publish runtime'
         required: false
         type: boolean
-        default: false
-      PUBLISH_VERSIOIN:
-        description: 'Publish version'
-        required: true
-        default: "0.2.0"
+        default: true
       PUBLISH_RELEASE:
         description: 'Publish release'
         type: boolean
         required: false
-        default: false
+        default: true        
+      PUBLISH_VERSIOIN:
+        description: 'Publish version'
+        required: true
+        default: "0.3.0"
 
 jobs:
 
@@ -43,12 +43,13 @@ jobs:
         id: set-components
         run: |
           # check publish version x.y.z
-          if [[ ! "${{ inputs.PUBLISH_VERSIOIN }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid version format. Expected x.y.z"
-            exit 1
-          fi
+          
           # check inputs must easysearch or runtime or both
           if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            if [[ ! "${{ inputs.PUBLISH_VERSIOIN }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Invalid version format. Expected x.y.z"
+              exit 1
+            fi
             # check if the inputs are set
             if [[ "${{ inputs.PUBLISH_EASYSEARCH }}" == 'true' ]] && [[ "${{ inputs.PUBLISH_RUNTIME }}" == 'true' ]]; then
               COMPONENTS="easysearch,runtime"
@@ -147,7 +148,7 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Docker build meta with ${{ matrix.component }}
+      - name: Docker build meta with ${{ matrix.component }}-${{env.IMAGE_TYPE}}
         id: tags
         working-directory: ${{ github.workspace }}/${{ env.PNAME }}
         run: |
