fix: the curl usr for test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -78,17 +78,17 @@ jobs:
           echo "   GET IP: ${IP:-NULL}"
 
           echo -e "\n🔌 noproxy:"
-          curl -s -I -o /dev/null -w "   HTTP: %{http_code}, IP: %{remote_ip}\n" --noproxy '*' "$BASE_URL" || echo "   Failed"
+          curl -s -I -o /dev/null -w "   HTTP: %{http_code}, IP: %{remote_ip}\n" --noproxy '*' "$RELEASE_URL" || echo "   Failed"
           echo "   proxy:"
-          curl -s -I -o /dev/null -w "   HTTP: %{http_code}, IP: %{remote_ip}\n" "$BASE_URL" || echo "   Failed"
+          curl -s -I -o /dev/null -w "   HTTP: %{http_code}, IP: %{remote_ip}\n" "$RELEASE_URL" || echo "   Failed"
 
           echo -e "\n🔗 Connect:"
-          curl -v --connect-timeout 5 "$BASE_URL/.latest" 2>&1 | \
+          curl -v --connect-timeout 5 "$RELEASE_URL/.latest" 2>&1 | \
             grep -E "Connected|resolve|Trying|SSL" | head -10
 
-          echo "$BASE_URL"
-          curl -v --connect-timeout 5 "$BASE_URL"
-          
+          echo "$RELEASE_URL"
+          curl -v --connect-timeout 5 "$RELEASE_URL"
+
           AGENT_VER=$(curl $RELEASE_URL/.latest |jq -r ".${DNAME}")
           echo "Get latest agent verion $AGENT_VER"
 
