chore: add network testing

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,6 +36,11 @@ on:
         required: false
         type: boolean
         default: false
+      TEST_NETWORK:
+        description: 'Test upload file'
+        required: false
+        type: boolean
+        default: false
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -52,6 +57,26 @@ jobs:
           echo "This is a test artifact" > test-artifact.txt
           oss upload -c "$GITHUB_WORKSPACE/.oss.yml" -f test-artifact.txt -p $DNAME && \
           oss delete -c "$GITHUB_WORKSPACE/.oss.yml" -p $DNAME -k test-artifact.txt
+
+      - name: Check Network
+        if: ${{ inputs.TEST_NETWORK == true }}
+        run: |
+          HOST=$(echo "$RELEASE_URL" | sed 's|https\?://||' | cut -d'/' -f1)
+          IP=$(getent hosts $HOST | awk '{print $1}')
+          echo "   DOMAIN：$HOST"
+          echo "   GET IP: ${IP:-NULL}"
+
+          echo -e "\n🔌 noproxy:"
+          curl -s -I -o /dev/null -w "   HTTP: %{http_code}, IP: %{remote_ip}\n" --noproxy '*' "$BASE_URL" || echo "   Failed"
+          echo "   proxy:"
+          curl -s -I -o /dev/null -w "   HTTP: %{http_code}, IP: %{remote_ip}\n" "$BASE_URL" || echo "   Failed"
+
+          echo -e "\n🔗 Connect:"
+          curl -v --connect-timeout 5 "$BASE_URL/.latest" 2>&1 | \
+            grep -E "Connected|resolve|Trying|SSL" | head -10
+
+          AGENT_VER=$(curl $RELEASE_URL/.latest |jq -r ".${DNAME}")
+          echo "Get latest agent verion $AGENT_VER"
 
       - name: Get github release versions
         env:
